Update to ROS2 Humble version
g0mb4/ksp_bridge pull request #1
Opened 2023-10-17 00:41 UTC by clausqr

Update to:
+ KSP 1.12.5
+ kRPC 0.5.2
+ ROS2 Humble
+ Ubuntu 22.04
Plus dockerization for easier installation.

2023-10-18 13:45 UTC, g0mb4 requested changes
Thanks for the update! I really like it, but I'd prefer to leave out Docker.  The installation steps from `Dockerfile` shoud be in the README.

2023-10-18 13:45 UTC, g0mb4 commented on ksp_bridge/src/ksp_bridge.cpp
> +    printf("Declaring parameter: %s\n", "celestial_bodies"  );
Why are you outputting this? Also `%s` expects a `const char*` not an `<std::vector<std::string>`.

2023-10-18 13:45 UTC, g0mb4 commented on Dockerfile
> +RUN mkdir krpc && \
Nice addition, but I'd prefer it in the README, not in a Dockerfile.

2023-10-18 13:45 UTC, g0mb4 commented on README.md
> +xhost +local:docker
Can you please leave out docker?

2023-10-18 13:45 UTC, g0mb4 commented on ksp_bridge/src/ksp_bridge.cpp
> +    printf("Declared parameter: %s\n", "celestial_bodies"  );
Same as above.

2023-10-20 01:16 UTC, clausqr commented
Moved docker to a separate branch and removed debugging artifacts.

2023-10-20 07:35 UTC, g0mb4 commented
Thanks for the updates! Only one thing is missing form the updated readme: the installation of the updated GameData files.

The old step was this:
> 
> ```bash
> mkdir krpc; cd krpc
> wget https://github.com/nullprofile/krpc/releases/download/0.4.9-1.12.1/krpc-0.4.9-1.12.1.zip
> unzip krpc-0.4.9-1.12.1.zip
> ```
> 
> Copy the *GameData/kRPC* directory into the *GameData* directory of Kerbal Space Program.
> The path can be obtained through Steam (Right Click->Manage->Browse local files).

I did not use the official repo, because I did not find precompiled GameData objects at the time.
Can you please find a precompiled kRPC 1.12.5 (or add insturctions on how to compile one)?

2023-10-20 08:09 UTC, g0mb4 requested changes
Thanks for the updates! Only one thing is missing form the updated readme: the installation of the updated GameData files.

The old step was this:
> 
> ```bash
> mkdir krpc; cd krpc
> wget https://github.com/nullprofile/krpc/releases/download/0.4.9-1.12.1/krpc-0.4.9-1.12.1.zip
> unzip krpc-0.4.9-1.12.1.zip
> ```
> 
> Copy the *GameData/kRPC* directory into the *GameData* directory of Kerbal Space Program.
> The path can be obtained through Steam (Right Click->Manage->Browse local files).

I did not use the official repo, because I did not find precompiled GameData objects at the time.
Can you please find a precompiled kRPC 0.5.2 (or add insturctions on how to compile one)?

2026-04-24 12:23 UTC, closed without merging